name: Project Enhancement Request
description: Suggest your enhancement for the existing game 
title: "[Feature Request]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature enhancement request form
        
        
  - type: textarea
    id: description
    attributes:
      label: How would you like to enhance the existing project.
      description: Enter a brief description about the feature you feel is required.
      placeholder: Give all the context of your enhancement as well as the existing project.
      value: "Enhancement"
    validations:
      required: true
      
      
  - type: textarea
    id: behaviour
    attributes:
      label: Describe breifly how would you implement the same.
      description: Give a brief description by which you will solve it.
      placeholder: Please include a summary, also include relevant motivation and context. 
      value: "Solution_steps"
    validations:
      required: true
      
      
  - type: dropdown
    id: contribution
    attributes:
      label: Are you contributing for a program?
      multiple: true
      options:
        - GSSoC23
        - Other
        
        
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our contibuting guideline[CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md)
      options:
        - label: I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.
          required: true
