name: "🐞 Bug Report"
description: Create a new ticket for a bug.
title: "🐞 [BUG] - Title"
labels: [
  "bug"
]
body:
  - type: markdown
    attributes:
      value: |
        🐞 **Bug Report**

        Thanks for taking the time to fill out this bug report! :memo:

        :information_source: Before submitting the report, please make sure to read our contributing guidelines. By submitting this issue, you agree to follow our guidelines. :book:

        :link: [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md)

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: currentBehavior
    attributes:
      label: "Current behaviour"
      description: What happens, e.g. "The price shown on the button is £400"
      placeholder: Short and explicit description of current senario...
    validations:
      required: true
  - type: textarea
    id: expectedBehaviour
    attributes:
      label: "Expected behaviour"
      description: What should happen, e.g. "The price shown on the button is £4"
      placeholder: Short and explicit description of what should happen...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)  
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: "Browsers"
      description: What browsers are you seeing the problem on ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment ?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false
  - type: dropdown
    id: contribution
    attributes:
      label: Are you contributing for a program ?
      multiple: true
      options:
        - GSSoC2023
        - Other
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our contributing guidelines. Please read our [Contributing Guidelines](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md).
      options:
        - label: I have read and agree to the Contributing Guidelines of this project.
          required: true

      