name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        
  - type: textarea
    id: bug-description
    attributes:
      label: Give a brief about the bug discovered✍
      description: Enter a brief description about the bug report
      placeholder: Please include a summary, also include relevant motivation and context. 
      value: "Description"
    validations:
      required: true
      
      
  - type: textarea
    id: behaviors
    attributes:
      label: What is the expected behavior?
      description: Also tell us, what did you expect to happen, if bug was not present?
      placeholder: Please include a summary, also include relevant motivation and context. 
      value: "Description"
    validations:
      required: true
      
      
  - type: textarea
    id: instructions
    attributes:
      label: Give a brief description to get the expect behaviour.
      description: Enter the brief description on how you plan to find the bug's solution
      placeholder: Please include a summary, also include relevant motivation and context. 
      value: "Description"
    validations:
      required: true
      
      
  - type: dropdown
    id: contribution
    attributes:
      label: Are you contributing for a program?
      multiple: true
      options:
        - GSSoC2023
        - Other
        
        
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our contibuting guideline[CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md)
      options:
        - label: I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.
          required: true
